name: Docker Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  # schedule: 
  # - cron: "*/1 * * * *"
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: test-app

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
      
      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
      
      - name: Docker Publish
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
  
  deploy:
    needs: docker
    concurrency:  #remove this 👈
      group: production-deployment  #remove this 👈
      cancel-in-progress: true  #remove this 👈
    runs-on: ubuntu-latest
    
    steps:
      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
      
      - name: Docker Run
        run: |
          docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          sleep 300s 
        #