name: Matrix Configuration

on:
  push: 
  workflow_dispatch:

jobs: 
  deploy:
    environment: prod
    strategy: 
      matrix: 
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:  #remove this 👈 #excluding alpine image on windows os
          - images: alpine #remove this 👈
            os: windows-latest #remove this 👈

    runs-on: ${{ matrix.os }}

    steps: 
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}