name: Matrix Configuration

on:
  push: 
  workflow_dispatch:

jobs: 
  deploy:
    strategy: 
      matrix: #remove this 👈
        os: [ubuntu-latest, ubuntu-20.04, windows-latest] #remove this 👈
        images: [hello-world, alpine] #remove this 👈

    runs-on: ${{ matrix.os }} #remove this 👈 # referencing the os defined by the matrix above

    steps: 
      - name: Echo Docker Details
        run: docker info

    
      - name: Run Images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}